#!/bin/bash

# check init system
if [ -d "/run/systemd/system" ]; then
    mv /opt/ss/ssm-client/systemd/* /lib/systemd/system/
    rm -rf /opt/ss/ssm-client/init.d /opt/ss/ssm-client/init /opt/ss/ssm-client/systemd
elif [ -f "/sbin/upstart-udev-bridge" ] || ([ -f "/sbin/init" ] && [ "$(/sbin/init --version)" == "init (upstart"* ]); then
    mv /opt/ss/ssm-client/init/* /etc/init/
    rm -rf /opt/ss/ssm-client/init.d /opt/ss/ssm-client/init /opt/ss/ssm-client/systemd
else
    mv /opt/ss/ssm-client/init.d/* /etc/init.d/
    rm -rf /opt/ss/ssm-client/init.d /opt/ss/ssm-client/init /opt/ss/ssm-client/systemd
fi