#!/bin/bash
# uninstall
if [ "$1" = "remove" ]; then
    rm -rf /opt/ss/ssm-client
    rm -rf /opt/ss/qan-agent
    rm -f /lib/systemd/system/ssm-*
    rm -f /etc/init.d/ssm-*
    rm -f /etc/init/ssm-*
    echo "Uninstall complete."
fi
