#!/usr/bin/env bash

set -eu

PMM_DIR="/opt/ss/ssm-client"
QAN_DIR="/opt/ss/qan-agent"

if [ $(id -u) -ne 0 ]; then
    echo "The script requires superuser privileges."
    exit 1
fi

# Clean up invalid dir created in v1.7.2
if [ -d "$PMM_DIR/textfile_collector" ]; then
   rm -rf $PMM_DIR/textfile_collector
fi

mkdir -p $PMM_DIR $QAN_DIR/bin $PMM_DIR/textfile-collector

# delete old symlink
rm -f /usr/sbin/ssm-admin

cp -f bin/ssm-admin /usr/sbin/
ln -s /usr/sbin/ssm-admin /usr/sbin/pmm-admin
cp -f bin/node_exporter $PMM_DIR/
cp -f bin/mysqld_exporter $PMM_DIR/
cp -f bin/postgres_exporter $PMM_DIR/
cp -f bin/mongodb_exporter $PMM_DIR/
cp -f bin/proxysql_exporter $PMM_DIR/
cp -f bin/ssm-qan-agent $QAN_DIR/bin/
ln -s $QAN_DIR/bin/ssm-qan-agent $QAN_DIR/bin/percona-qan-agent
cp -f bin/ssm-qan-agent-installer $QAN_DIR/bin/
ln -s $QAN_DIR/bin/ssm-qan-agent-installer $QAN_DIR/bin/percona-qan-agent-installer
cp -f bin/pt-summary $QAN_DIR/bin/
cp -f bin/pt-mongodb-summary $QAN_DIR/bin/
cp -f bin/pt-mysql-summary $QAN_DIR/bin/
install -m 0644 queries-mysqld.yml $PMM_DIR/
install -m 0755 example.prom $PMM_DIR/textfile-collector/
